config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "download", to: "pages#download"
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  validates :name, :email, :subject, :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def download
    send_file(
      "#{Rails.root}/app/assets/files/CV_FUNG_Yong_How.pdf",
      filename: "CV_FUNG_Yong_How.pdf",
      type: "application/pdf"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YHF | Full-Stack Developer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path("favicon-32x32-removebg.png"), rel: 'icon', type: 'image/png' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%# Top %>
<div class="container">
  <div class="banner" id="top">
    <div class="container text-center">
      <h1 class="title-animation">Hello! <br class="br"> I'm Yong How!</h1>
      <p><span data-controller="typed-js"></span></p>
      <%= link_to "Download", download_path, class: "btn btn-gradient draw", target: "_blank" %>
    </div>
    <div class="contact-links">
      <ul>
        <li>
          <a href="https://github.com/yhfung-git" target="_blank"><i class="fab fa-github"></i></a>
        </li>
        <li>
          <a href="mailto:contact@yhfung.click?subject=yhfung.click | Contact Form" target="_blank"><i class="fa-solid fa-envelope"></i></a>
        </li>
        <li>
          <a href="https://www.linkedin.com/in/yhfung/" target="_blank"><i class="fab fa-linkedin"></i></a>
        </li>
      </ul>
    </div>
    <div class="d-flex justify-content-center flex-column align-items-center">
    <img src="<%= asset_path("Myself.jpg")%>" style="margin: 15px 0 15px 0; height: 250px; width: 250px; border-radius: 50%;">
      <div class="mouse mt-4"></div>
      <p class="mouse-p">Scroll</p>
    </div>
  </div>

  <hr class="mt-5" style="color: #1BA098;">

  <%# Projects %>
  <div>
    <h1 class="text-center title-animation mt-5" id="Projects">Projects</h1>
    <div class="projects-container mb-5">
      <div class="logo">
        <%= link_to "https://speakitout.herokuapp.com/", target: "_blank" do %>
          <img src="https://speakitout.herokuapp.com/assets/nav_bar-3f593ad566affb8edb65bb9ee16f549e63745ac29c01fd491fa728c74f089249.png" alt="Speakitout" class="project-image">
        <% end %>
        <p>Spe@kitOut<br><small><em>Le Wagon</em></small></p>
      </div>
      <div class="logo">
        <%= link_to "https://yhfung-git.github.io/rock-paper-scissors/", target: "_blank" do %>
          <%= image_tag("rock-paper-scissors.jpg", alt: "rock-paper-scissors", class:"project-image") %>
        <% end %>
        <p>Rock-Paper-Scissors<br><small><em>The Odin Project</em></small></p>
      </div>
      <div class="logo">
        <%= link_to "https://yhfung-git.github.io/etch-a-sketch/", target: "_blank" do %>
          <%= image_tag("etch-a-sketch.png", alt: "etch-a-sketch", class:"project-image") %>
        <% end %>
        <p>Etch-a-Sketch<br><small><em>The Odin Project</em></small></p>
      </div>
      <div class="logo">
        <%= link_to "https://yhfung-git.github.io/react-giphy-challenge/", target: "_blank" do %>
          <%= image_tag("gif.png", alt: "react-giphy-challenge", class:"project-image", style:"background-color:white") %>
        <% end %>
        <p>React-Giphy<br><small><em>Le Wagon</em></small></p>
      </div>
      <div class="logo">
        <%= link_to "https://yhfung-git.github.io/redux-chat-challenge/", target: "_blank" do %>
          <%= image_tag("chatbox.png", alt: "redux-chat-challenge", class:"project-image", style:"background-color:white") %>
        <% end %>
        <p>Redux-Chatbox<br><small><em>Le Wagon</em></small></p>
      </div>
    </div>
  </div>

  <hr style="color: #1BA098;">

  <%# About %>
  <div class="banner" style="padding-top: 0;">
    <div class="skills">
      <%= render "shared/hard_skills" %>
      <div class="row my-5">
        <div class="col-12 col-md-6 col-lg-4 skills-content" id="soft-skills">
          <h1 class="mt-3">soft skills</h1>
          <ul>
            <li>Team Player</li>
            <li>Adaptability</li>
            <li>Organization</li>
            <li>Detail-oriented</li>
            <li>Versatility</li>
            <li>Autonomy</li>
          </ul>
        </div>
        <div class="col-12 col-md-6 col-lg-4 skills-content" id="languages">
          <h1 class="mt-3">languages</h1>
          <ul>
            <li>Chinese</li>
            <li>English</li>
            <li>French</li>
            <li>Malay</li>
            <li>Hakka</li>
            <li>Cantonese</li>
          </ul>
        </div>
        <div class="col-12 col-md-6 col-lg-4 skills-content" id="hobbies">
          <h1 class="mt-3">hobbies</h1>
          <ul>
            <li>Sports</li>
            <li>Travel</li>
            <li>Photography</li>
            <li>Video Editing</li>
          </ul>
        </div>
      </div>
    </div>
    <h1 class="text-center title-animation my-5">About Me</h1>
    <%= render "shared/timeline" %>
  </div>

  <hr class="mt-5 mb-0" style="color: #1BA098;">

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <%# <h1 class="title-animation mt-4" style="text-align: center;" id="Contact">Contact</h1> %>
  <div class="footer-copyright">
    <p>Copyright ©2022-<%= Date.today.year %> yhfung.click. All Rights Reserved.</p>
  </div>
</div>

app/views/shared/_hard_skills.html.erb
<section id="hard-skills">
  <h1 class="mb-5 skills-content" id="About">hard skills</h1>
  <div class="row">
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 skills-content">
      <%# Front-end %>
      <h2>Front-end</h2>
      <ul>
        <li>HTML</li>
        <li>CSS</li>
        <li>SCSS</li>
        <li>Bootstrap</li>
        <li>JavaScript</li>
        <li>React</li>
        <li>Stimulus</li>
        <li>Webpack</li>
      </ul>

      <%# Back-end %>
      <div class="addition-padding">
        <h2>Back-end</h2>
        <ul>
          <li>Ruby</li>
          <li>Ruby on Rails</li>
        </ul>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 skills-content">
      <%# Database %>
      <h2>Database</h2>
      <ul>
        <li>SQL</li>
        <li>SQLite</li>
        <li>PostgreSQL</li>
      </ul>

      <%# Video Editing %>
      <div class="addition-padding">
        <h2>Video Editing</h2>
        <ul>
          <li>Adobe Premiere</li>
          <li>Filmora</li>
        </ul>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 skills-content">
      <%# UI/UX %>
      <h2>UI/UX</h2>
      <ul>
        <li>Figma</li>
        <li>Canva</li>
        <li>StarUML</li>
      </ul>

      <%# Agile %>
      <div class="addition-padding">
        <h2>Agile</h2>
        <ul>
          <li>Scrum</li>
        </ul>
      </div>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 skills-content">
      <%# Tools %>
      <h2>Tools</h2>
      <ul>
        <li>Git & GitHub</li>
        <li>VSCode</li>
        <li>Trello</li>
        <li>Slack</li>
        <li>CLI (Ubuntu)</li>
        <li>Heroku</li>
        <li>Netlify</li>
        <li>Cloudinary</li>
        <li>Mapbox</li>
        <li>PowerPoint</li>
        <li>Word</li>
        <li>Excel</li>
        <li>Google Slides</li>
      </ul>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="navbar" data-action="scroll@window->navbar#activeNavbar">
  <div class="container-fluid">
    <a class="navbar-brand pulse" href="#top">
      <img src="<%= asset_path("logo-512x512-removebg.png") %>"/>
    </a>
    <div class="navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#About">About</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#Projects">Projects</a>
        </li>
        <%# <li class="nav-item active">
          <a class="nav-link" href="#Contact">Contact</a>
        </li> %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_timeline.html.erb
<h1 class="text-center timeline-title">Education</h1>
<section class="timeline">
  <ul>
    <li>
      <div>
        <time>Oct 2022 - Dec 2022</time>
        <div>
          <h1>PROFESSIONAL TITLE OF WEB APPLICATION DEVELOPER/ DESIGNER</h1>
          <p><i class="fa-solid fa-location-dot"></i>Le Wagon Marseille - Bootcamp - #1064</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Titre Professionnel de Développeur / Concepteur d'Application Web</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Jan 2022</time>
        <div>
          <h1>MANAGING DIFFICULT SITUATIONS WHILE FACING MY CLIENTS</h1>
          <p><i class="fa-solid fa-location-dot"></i>Academy Accor France</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Gérer les situations difficiles face à mon client</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Sep 2018 - Dec 2019</time>
        <div>
          <h1>Diploma in French Language and Culture</h1>
          <p><i class="fa-solid fa-location-dot"></i>University Aix-Marseille, Aix-en-Provence</p>
          <p><i class="fa-solid fa-thumbs-up"></i> Diplôme d’Université de Langue et Culture Françaises - Level B1</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Jan 2016 - Sep 2017</time>
        <div>
          <h1>GUEST RELATIONS TRAINING</h1>
          <p><i class="fa-solid fa-location-dot"></i>Bunc Hostel in Singapore</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Jan 2013 - Sep 2014</time>
        <div>
          <h1>Diploma in Hospitality & Tourism Management</h1>
          <p><i class="fa-solid fa-location-dot"></i>Southern University College in Malaysia and Coleman College in Singapore</p>
        </div>
      </div>
    </li>
  </ul>
</section>

<h1 class="text-center timeline-title mt-5">Experience</h1>
<section class="timeline">
  <ul>
    <li>
      <div>
        <time>Oct 2021 - Aug 2022</time>
        <div>
          <h1>Hotel Receptionist</h1>
          <p><i class="fa-solid fa-location-dot"></i>Ibis Hotel at La Ciotat, 86 rooms</p>
          <p><i class="fa-solid fa-thumbs-up"></i>All aspects of receptionist's duties</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Bar and pool services</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Setup meeting room</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Feb 2021 - Oct 2021</time>
        <div>
          <h1>Hotel Receptionist</h1>
          <p><i class="fa-solid fa-location-dot"></i>Corniche du Liouquet Hotel at La Ciotat, 15 rooms</p>
          <p><i class="fa-solid fa-thumbs-up"></i>All aspects of receptionist's duties</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Garden, Laundry, Breakfast, etc...</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Dec 2020 - Jan 2021</time>
        <div>
          <h1>Crew</h1>
          <p><i class="fa-solid fa-location-dot"></i>Lidl at La Ciotat</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Arrange and fill up the fridge</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Ensuring the quality and freshness of the products</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Aug 2020 - Nov 2020</time>
        <div>
          <h1>Hotel Receptionist</h1>
          <p><i class="fa-solid fa-location-dot"></i>Sure Hotel by Best Western Coeur De Cassis, 28 rooms</p>
          <p><i class="fa-solid fa-thumbs-up"></i>All aspects of receptionist's duties</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Coordinate with other Best Western hotels</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Feb 2018 - Sep 2018</time>
        <div>
          <h1>Hotel Receptionist</h1>
          <p><i class="fa-solid fa-location-dot"></i>Quarters Hostel in Singapore, 86 beds</p>
          <p><i class="fa-solid fa-thumbs-up"></i>All aspects of receptionist's duties</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Competitor analysis</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Relations with suppliers and travel agencies</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Jan 2015 - Sep 2017</time>
        <div>
          <h1>Hotel Receptionist</h1>
          <p><i class="fa-solid fa-location-dot"></i>Bunc Hostel in Singapore, 330 beds</p>
          <p><i class="fa-solid fa-thumbs-up"></i>All aspects of receptionist's duties</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Breakfast, Ordering, etc...</p>
        </div>
      </div>
    </li>
    <li>
      <div>
        <time>Jun 2014 - Sep 2014</time>
        <div>
          <h1>Bartender Internship</h1>
          <p><i class="fa-solid fa-location-dot"></i>Club Med Cherating in Malaysia, 297 rooms</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Set up alcohol events</p>
          <p><i class="fa-solid fa-thumbs-up"></i>Take orders and serve drinks</p>
        </div>
      </div>
    </li>
  </ul>
</section>